### ISSUE TITLE
请问这个要怎么用呀？

### ISSUE THREAD

**Issue by qingwen-guan** [baobao1270/vscode-markdown-mindmap-preview#2]

**Comment by baobao1270** [comment]
# 基本用法
1. 在 VSCode 里安装本插件
2. 用 VSCode 打开一个 `.md` 文件
3. 在编辑界面右上角，有一个思维导图的图标。点击它。

# 使用命令
1. 按 `Ctrl+Shift+P`，可以进入命令输入模式
2. 输入 `showMindMap` 可以显示思维导图
3. 在显示思维导图时，使用命令 `exportSvg` 导出到 SVG 图像。SVG 图形保存为 Markdown 文件所在文件夹下与之同名的文件。

```
//TDDO：在 README 中进行用法介绍
```
