### ISSUE TITLE
有可能实现在右边的思维导图上点击右键(?)则左边的光标自动移动到相应的位置么?

### ISSUE THREAD

**Issue by qingwen-guan** [baobao1270/vscode-markdown-mindmap-preview#3]

**Comment by baobao1270** [comment]
这个实现难度比较大，但是将列入开发计划，优先级于支持各种格式的图片导出和初步完善文档之后。

**Comment by qingwen-guan** [comment]
> 这个实现难度比较大，但是将列入开发计划，优先级于支持各种格式的图片导出和初步完善文档之后。

有大概的排期咩？比如说 一个月后? 一个Q后? 还是一年后?

**Comment by qingwen-guan** [comment]
效果可以参考: https://twitter.com/chrissanders88/status/1306262108665982976?s=19

**Comment by baobao1270** [comment]
抱歉，最近忙着考研，本项目暂时没有精力维护了。如果未来有机会，可能会继续维护，并进行重构。感谢您的支持。 #9
