### ISSUE TITLE
第一次打开的时候，会出现Rendering Please Wait，要关掉重新开才能好。

### ISSUE THREAD

**Issue by qingwen-guan** [baobao1270/vscode-markdown-mindmap-preview#4]

**Comment by baobao1270** [comment]
我这里无法复现，请您提供一下详细信息：
 - 您的操作系统版本：
 - 您的 VSCode 版本：
 - 您的 `vscode-markdown-mindmap-preview` 插件版本：
 - 复现步骤：
 - 如果可用，是否有调试日志：
谢谢！

**Comment by baobao1270** [comment]
由于您长期没有回复，且本问题无法复现，此 Issue 将关闭。回复本问题即可重新打开此 Issue。
