### ISSUE TITLE
[ZH][FRQ]带序号的内容保留序号

### ISSUE THREAD

**Issue by jaybowang** [baobao1270/vscode-markdown-mindmap-preview#5]
**提交前检查单**
 - 您是否已详阅文档，并确认目前本项目无法满足您的需求？『是』
 - 您是否已检索 issue，确保此此前未有类似之功能建议？『是』
 - 请尽量使用『全角空心引号』以保持格式一致，谢谢！『好的，我会遵守』

**简述此功能将解决的问题**
比如
```
把养乐多放进冰箱执行步骤
1. 打开冰箱
1. 放进养乐多
1. 关闭冰箱
```
目前生成的图：
<img width="471" alt="iShot2020-10-08 15 51 01" src="https://user-images.githubusercontent.com/1948533/95430314-3387d000-097e-11eb-93d7-0c48e09778d2.png">

希望生成的图：
<img width="544" alt="iShot2020-10-08 15 51 33" src="https://user-images.githubusercontent.com/1948533/95430339-3d113800-097e-11eb-8b5e-0b0d00c35d07.png">

带序号的好处：
- 方便引用，比如讨论的时候可以直接说第几项
- 一看就知道有多少项，不用数

**解决方案**
带序号的`1. `生成的导图中增加序号
不带序号的`- `继续保留现在的效果即可

**Comment by baobao1270** [comment]
非常抱歉，带序号的内容渲染属于引用的第三方开源渲染引擎的内部行为。由于该引擎未暴露修改内部节点的相关 API，而本项目短期内也没有更换渲染引擎的计划，此功能短期内不可实现。

目前您使用 hack 方法解决此问题。如：

```
1. 一、打开冰箱
2. 二、放入大象
3. 三、关闭冰箱
```

此 hack 方法同时也解决了需要更换序号数字格式和项目符号的问题。

感谢您的建议，若本项目将来更换或自己编写渲染引擎，将重新考虑您的提议。若您有意自己以代码实现本功能，也欢迎您提交 PR。
