### ISSUE TITLE
[ZH][BUG] Running the contributed command: 'mdmmp.showMindMap' failed

### ISSUE THREAD

**Issue by quanzaiyu** [baobao1270/vscode-markdown-mindmap-preview#6]
**提交前检查单**
 - 您是否已检索已有的 issue 并尝试解决问题？『是』
 - 您是否已详阅文档与 README 中的『已知错误』？『是』
 - 您是否已将 VSCode 与本插件更新至最新稳定版本？『是』
 - 您的操作系统名称和版本：『Windows 10 2004』
 - 您的 VSCode 版本：『1.50.1』
 - 您的 `vscode-markdown-mindmap-preview` 插件版本：『v1.1.0』
 - 请尽量使用『全角空心引号』以保持格式一致，谢谢！『好的，我会遵守』

**描述**

执行 `View Mind Map` 命令报错：

```
命令"View Mind Map"导致错误 (Running the contributed command: 'mdmmp.showMindMap' failed.)
```

![image](https://user-images.githubusercontent.com/13745132/96534855-27c3d400-12c3-11eb-97a7-0d870b95b521.png)

**重现步骤**
 1. 打开一个 md 文件，内容类似：

```md
## 测试
- Frontend
  - HTML
  - CSS
  - JavaScript
```

 2. `Ctrl + Shift + P` 调出命令面板
 3. 输入 `View Mind Map`，并回车执行此命令
 4. 报上述错误

**Comment by baobao1270** [comment]
抱歉本问题在相同环境下无法复现，请您
 - 检查文件系统权限
 - 打开 VSCode 的开发者工具并记录日志，谢谢！

**Comment by baobao1270** [comment]
由于您长期没有回复，且本问题无法复现，此 Issue 将关闭。回复本问题即可重新打开此 Issue。

**Comment by AngusWG** [comment]
v1.3.0 把中文插件关掉就好了
