### ISSUE TITLE
[ZH][BUG] sorry the actice text editor is not valid.

### ISSUE THREAD

**Issue by zhaojinzhou** [baobao1270/vscode-markdown-mindmap-preview#7]
**提交前检查单**
 - 您是否已检索已有的 issue 并尝试解决问题？『是』
 - 您是否已详阅文档与 README 中的『已知错误』？『是』
 - 您是否已将 VSCode 与本插件更新至最新稳定版本？『是』
 - 您的操作系统名称和版本：『』
 - 您的 VSCode 版本：『』
 - 您的 `vscode-markdown-mindmap-preview` 插件版本：『』
 - 请尽量使用『全角空心引号』以保持格式一致，谢谢！『好的，我会遵守』

**描述**
导出 为svg时遇到  报错。

**sorry the actice text editor is not valid.**

请在此简述此异常。（此行可删除）

**重现步骤**
 1. ...
 2. ...

**期望行为**

请简述您期望的程序行为『可选』（此行可删除）

**截图**

『可选』（此行可删除）![image](https://user-images.githubusercontent.com/16334836/105687664-addf5e80-5f33-11eb-9a54-61e7e10d1618.png)

**日志**

请使用 `Ctrl+Shift+I` 快捷键打开调试控制台，将有关的日志粘贴在下方：
```
```

请使用 `Ctrl+Shift+P` 打开命令栏，并输入命令 `>developer: open webview developer tools`，将有关的日志粘贴在下方：
```
```

**Comment by baobao1270** [comment]
抱歉，最近忙着考研，本项目暂时没有精力维护了。如果未来有机会，可能会继续维护，并进行重构。感谢您的支持。 #9

**Comment by baobao1270** [comment]
抱歉，最近忙着考研，本项目暂时没有精力维护了。如果未来有机会，可能会继续维护，并进行重构。感谢您的支持。 #9
